config/routes.rb
Rails.application.routes.draw do
  resources :azuls do
    collection do
      get 'page_forwarding_mode'
      post 'forward_to_azul_payment_page'
      get 'approved'
      get 'declined'
      get 'canceled'
      post 'response_post'
      get 'api_mode'
      post 'make_payment_by_azul_api'
      get 'get_auth_hash'
    end
  end
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'azuls#page_forwarding_mode'
  devise_for :users
end

app/models/azul.rb
class Azul < ApplicationRecord
end

app/controllers/azuls_controller.rb
class AzulsController < ApplicationController
  before_action :set_azul, only: [:show, :edit, :update, :destroy]

  # GET /azuls
  # GET /azuls.json
  def index
    @azuls = Azul.all
  end

  # GET /azuls/1
  # GET /azuls/1.json
  def show
  end

  # GET /azuls/new
  def new
    @azul = Azul.new
  end

  # GET /azuls/1/edit
  def edit
  end

  # POST /azuls
  # POST /azuls.json
  def create
    @azul = Azul.new(azul_params)

    respond_to do |format|
      if @azul.save
        format.html { redirect_to @azul, notice: 'Azul was successfully created.' }
        format.json { render :show, status: :created, location: @azul }
      else
        format.html { render :new }
        format.json { render json: @azul.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /azuls/1
  # PATCH/PUT /azuls/1.json
  def update
    respond_to do |format|
      if @azul.update(azul_params)
        format.html { redirect_to @azul, notice: 'Azul was successfully updated.' }
        format.json { render :show, status: :ok, location: @azul }
      else
        format.html { render :edit }
        format.json { render json: @azul.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /azuls/1
  # DELETE /azuls/1.json
  def destroy
    @azul.destroy
    respond_to do |format|
      format.html { redirect_to azuls_url, notice: 'Azul was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def page_forwarding_mode
    @azul = Azul.first
    if !@azul.present?
      @azul = Azul.new
    end

  end

  def forward_to_azul_payment_page
    puts "params: #{params.inspect}"
  end

  def api_mode
    @azul_json = AzulJson.first
    if !@azul_json.present?
      @azul_json = AzulJson.new
    end
  end

  def make_payment_by_azul_api
    puts "==== params: #{params.inspect} ===="
    # save to database
    azul_json = AzulJson.first
    if azul_json.present?
      azul_json.update(azul_json_params)
    else
      azul_json = AzulJson.create(azul_json_params)
      azul_json.save!
    end
    body_data = azul_json_params_for_remote.to_json
    puts "===== azul_json_body_data: #{body_data}"
    # make POST request to azul.com.do
    make_post_req(azul_json, body_data)
    redirect_to api_mode_azuls_path
  end

  def approved
    puts "==== params: #{params.inspect} ===="
    flash[:notice] = t("AZUL approved successfully!")
    redirect_to page_forwarding_mode_azuls_path
  end

  def canceled
    puts "==== params: #{params.inspect} ===="
    flash[:error] = flash[:error] = "AZUL canceled!"
    redirect_to page_forwarding_mode_azuls_path
  end

  def declined
    puts "==== params: #{params.inspect} ===="
    flash[:error] = "AZUL declined."
    redirect_to page_forwarding_mode_azuls_path
  end

  def response_post
    puts "==== params: #{params.inspect} ===="
    flash[:notice] = t("AZUL sent you a respose!")
    redirect_to page_forwarding_mode_azuls_path
  end

  def get_auth_hash
    # save to database
    azul = Azul.first
    if azul.present?
      azul.update(azul_params_from_api)
    else
      azul = Azul.create(azul_params_from_api)
      azul.save!
    end
    # make auth_hash
    origin_auth =  "#{params[:merchant_id]}#{params[:merchant_name]}#{params[:merchant_type]}#{params[:currency]}#{params[:order_number]}#{params[:amount]}#{params[:approved_url]}#{params[:declined_url]}#{params[:cancel_url]}#{params[:response_post_url]}#{params[:custom_field_1]}#{params[:custom_field_1_label]}#{params[:custom_field_1_value]}#{params[:custom_field_2]}#{params[:custom_field_2_label]}#{params[:custom_field_2_value]}#{params[:auth_key]}"

    auth_hash = Digest::SHA512.hexdigest origin_auth
    render json: {auth_hash: auth_hash, origin_auth: origin_auth}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_azul
      @azul = Azul.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def azul_params
      params.require(:azul).permit(:merchant_id, :merchant_type, :merchant_name, :auth_key, :url_azul, :approved_url, :declined_url, :cancel_url, :response_post_url, :custom_field_1, :custom_field_1_label, :custom_field_1_value, :custom_field_2, :custom_field_2_label, :custom_field_2_value)
    end

    def azul_params_from_api
      params.permit(:merchant_id, :merchant_type, :merchant_name, :auth_key, :url_azul, :approved_url, :declined_url, :cancel_url, :response_post_url, :custom_field_1, :custom_field_1_label, :custom_field_1_value, :custom_field_2, :custom_field_2_label, :custom_field_2_value)
    end

    def azul_json_params_for_remote
      azul_json_parameters = params[:azul_json]
      azul_json_parameters[:rrn] = nil if !azul_json_parameters[:rrn].present? or azul_json_parameters[:rrn] == ''
      azul_json_parameters.permit(:channel, :store, :card_number, :expiration, :cvc, :pos_input_mode, :trx_type, :amount, :currency_pos_code, :payments, :plan, :original_date, :original_trx_ticket_nr, :customer_service_phone, :acquirer_ref_data, :order_number, :custom_order_id, :rrn, :e_commerce_url)
    end

    def azul_json_params
      azul_json_parameters = params[:azul_json]
      azul_json_parameters[:rrn] = nil if !azul_json_parameters[:rrn].present? or azul_json_parameters[:rrn] == ''
      azul_json_parameters.permit(:azul_json_url, :auth1, :auth2, :channel, :store, :card_number, :expiration, :cvc, :pos_input_mode, :trx_type, :amount, :currency_pos_code, :payments, :plan, :original_date, :original_trx_ticket_nr, :customer_service_phone, :acquirer_ref_data, :order_number, :custom_order_id, :rrn, :e_commerce_url)
    end

    def make_post_req(azul_json, body)
      require 'uri'
      require 'net/http'
      require 'net/https'
      require 'json'

      begin
        uri = URI.parse(azul_json.azul_json_url)
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        req = Net::HTTP::Post.new(uri.path, initheader = {'Content-Type' =>'application/json'})
        req['Auth1'] = azul_json.auth1
        req['Auth2'] = azul_json.auth2
        req.body = body
        puts "======== request: #{req.inspect}"
        res = http.request(req)
        puts "======== response: #{res.body}"
        response_data = JSON.parse(res.body)
        flash[:notice] = "request:\nauth1: #{azul_json.auth1}\nauth2: #{azul_json.auth2}\nrequest_body: #{body}\n\nresponse from azul: #{response_data}"
      rescue => e
        puts "==== failed #{e}"
        flash[:error] = "request:\nauth1: #{azul_json.auth1}\nauth2: #{azul_json.auth2}\nrequest_body: #{body}\n\nfailed payment: #{e}"
        response_data = nil
      end
    end
end

app/helpers/azuls_helper.rb
module AzulsHelper
end

app/views/azuls/_button_for_page_forwarding_mode.html.erb
<form action="#{@azul.url_azul}" method="post">
  <input type="hidden" id="MerchantId" name="MerchantId" value="#{@azul.merchant_id}" >
  <input type="hidden" id="MerchantName" name="MerchantName" value="#{@azul.merchant_name}" >
  <input type="hidden" id="MerchantType" name="MerchantType" value="#{@azul.merchant_type}" >
  <input type="hidden" id="CurrencyCode" name="CurrencyCode" value="#{@currency}" >
  <input type="hidden" id="itbis" name="itbis" value="#{@itbis.split('.').join}" >
  <input type="hidden" id="OrderNumber" name="OrderNumber" value="#{@order_number}" >
  <input type="hidden" id="Amount" name="Amount" value="#{@amount.split('.').join}" >
  <input type="hidden" id="ApprovedUrl" name="ApprovedUrl" value="#{@azul.approved_url}" >
  <input type="hidden" id="DeclinedUrl" name="DeclinedUrl" value="#{@azul.declined_url}" >
  <input type="hidden" id="CancelUrl" name="CancelUrl" value="#{@azul.cancel_url}" >
  <input type="hidden" id="ResponsePostUrl" name="ResponsePostUrl" value="#{@azul.response_post_url}" >
  <input type="hidden" id="UseCustomField1" name="UseCustomField1" value="#{@azul.custom_field_1}" >
  <input type="hidden" id="CustomField1Label" name="CustomField1Label" value="#{@azul.custom_field_1_label}" >
  <input type="hidden" id="CustomField1Value" name="CustomField1Value" value="#{@azul.custom_field_1_value}" >
  <input type="hidden" id="UseCustomField2" name="UseCustomField2" value="#{@azul.custom_field_2}" >
  <input type="hidden" id="CustomField2Label" name="CustomField2Label" value="#{@azul.custom_field_2_label}" >
  <input type="hidden" id="CustomField2Value" name="CustomField2Value" value="#{@azul.custom_field_2_value}" >
  <input type="hidden" id="AuthHash" name="AuthHash" value="#{Digest::SHA512.hexdigest @auth_hash}" >
  <input type="submit" value="Pay with Azul Payment Page">
</form>".html_safe

app/views/azuls/_form.html.haml
= form_for @azul do |f|
  - if @azul.errors.any?
    #error_explanation
      %h2= "#{pluralize(@azul.errors.count, "error")} prohibited this azul from being saved:"
      %ul
        - @azul.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :merchant_id
    = f.text_field :merchant_id
  .field
    = f.label :merchant_type
    = f.text_field :merchant_type
  .field
    = f.label :merchant_name
    = f.text_field :merchant_name
  .field
    = f.label :auth_key
    = f.text_field :auth_key
  .field
    = f.label :url_azul
    = f.text_field :url_azul
  .field
    = f.label :approved_url
    = f.text_field :approved_url
  .field
    = f.label :declined_url
    = f.text_field :declined_url
  .field
    = f.label :cancel_url
    = f.text_field :cancel_url
  .field
    = f.label :response_post_url
    = f.text_field :response_post_url
  .actions
    = f.submit 'Save'

app/views/azuls/_form_for_api_mode.html.haml
%div
  = form_for @azul_json, url: make_payment_by_azul_api_azuls_path, method: :post do |f|
    - if @azul_json.errors.any?
      #error_explanation
        %h2= "#{pluralize(@azul_json.errors.count, "error")} prohibited this azul from being saved:"
        %ul
          - @azul_json.errors.full_messages.each do |message|
            %li= message

    .form-group.form-group-custom
      .field.authform-fieldset
        = f.label :azul_json_url
        = f.text_field :azul_json_url, class: 'form-control', placeholder: 'e.g. https://pruebas.azul.com.do/webservices/JSON/Default.aspx'
      .field.authform-fieldset
        = f.label "Auth1 header value"
        = f.text_field :auth1, class: 'form-control', placeholder: 'e.g. ategix'
      .field.authform-fieldset
        = f.label "Auth2 header value"
        = f.text_field :auth2, class: 'form-control', placeholder: 'e.g. ategix'

    .form-group.form-group-custom
      .field.authform-fieldset
        = f.label :channel
        = f.text_field :channel, class: 'form-control', placeholder: 'e.g. EC'
      .fieldauthform-fieldset
        = f.label :store
        = f.text_field :store, class: 'form-control', placeholder: 'e.g. 39036630010'
      .field.authform-fieldset
        = f.label :card_number
        = f.text_field :card_number, class: 'form-control', placeholder: 'e.g. 4242424242424242'
      .field.authform-fieldset
        = f.label :expiration
        = f.text_field :expiration, class: 'form-control', placeholder: 'e.g. 202012'
      .field.authform-fieldset
        = f.label :cvc
        = f.text_field :cvc, class: 'form-control', placeholder: 'e.g. 123'
      .field.authform-fieldset
        = f.label :pos_input_mode
        = f.text_field :pos_input_mode, class: 'form-control', placeholder: 'e.g. E-Commerce'
      .field.authform-fieldset
        = f.label :trx_type
        = f.text_field :trx_type, class: 'form-control', placeholder: 'e.g. Sale / Refund / ...'
      .field.authform-fieldset
        = f.label :payments
        = f.text_field :payments, class: 'form-control', placeholder: 'e.g. 1 or 0'
      .field.authform-fieldset
        = f.label :plan
        = f.text_field :plan, class: 'form-control', placeholder: 'e.g. 0'
      .field.authform-fieldset
        = f.label :acquirer_ref_data
        = f.text_field :acquirer_ref_data, class: 'form-control', placeholder: 'e.g. 1'
      .field.authform-fieldset
        = f.label 'RRN'
        = f.text_field :rrn, class: 'form-control', placeholder: 'e.g. null'
      .field.authform-fieldset
        = f.label :customer_service_phone
        = f.text_field :customer_service_phone, class: 'form-control', placeholder: 'e.g. 809-111-2222'
      .field.authform-fieldset
        = f.label :order_number
        = f.text_field :order_number, class: 'form-control'
      .field.authform-fieldset
        = f.label 'E-Commerce Url'
        = f.text_field :e_commerce_url, class: 'form-control', placeholder: 'e.g. www.spaceup.com.do'
      .field.authform-fieldset
        = f.label :custom_order_id
        = f.text_field :custom_order_id, class: 'form-control', placeholder: 'e.g. ABC123'
    .form-group.form-group-custom
      .field.authform-fieldset
        = label_tag :amount
        = text_field_tag :amount, '720', html: {class: 'form-control'}
      .field.authform-fieldset
        = label_tag :itbis
        = text_field_tag :itbis, '180', html: {class: 'form-control'}

      = f.submit 'Send azul payment action', class: 'button right', id: "button-send-azul-payment-action"

app/views/azuls/_form_for_page_forwarding_mode.html.haml
%div
  = form_for @azul, url: forward_to_azul_payment_page_azuls_path, method: :post do |f|
    - if @azul.errors.any?
      #error_explanation
        %h2= "#{pluralize(@azul.errors.count, "error")} prohibited this azul from being saved:"
        %ul
          - @azul.errors.full_messages.each do |message|
            %li= message

    .form-group.form-group-custom
      .field.authform-fieldset
        = f.label :merchant_id
        = f.text_field :merchant_id, class: 'form-control', placeholder: 'e.g. 39036630010'
      .fieldauthform-fieldset
        = f.label :merchant_type
        = f.text_field :merchant_type, class: 'form-control', placeholder: 'e.g. Sale'
      .field.authform-fieldset
        = f.label :merchant_name
        = f.text_field :merchant_name, class: 'form-control', placeholder: 'e.g. Ategix'
      .field.authform-fieldset
        = f.label :auth_key
        = f.text_field :auth_key, class: 'form-control', placeholder: 'e.g. ategix'
      .field.authform-fieldset
        = f.label :url_azul
        = f.text_field :url_azul, class: 'form-control', placeholder: 'e.g. https://pruebas.azul.com.do/PaymentPage/'
    .form-group.form-group-custom
      .field.authform-fieldset
        = f.label :approved_url
        = f.text_field :approved_url, class: 'form-control', placeholder: 'e.g. [protocol]://[site address]/azuls/approved'
      .field.authform-fieldset
        = f.label :declined_url
        = f.text_field :declined_url, class: 'form-control', placeholder: 'e.g. [protocol]://[site address]/azuls/declined'
      .field.authform-fieldset
        = f.label :cancel_url
        = f.text_field :cancel_url, class: 'form-control', placeholder: 'e.g. [protocol]://[site address]/azuls/cancel'
      .field.authform-fieldset
        = f.label :response_post_url
        = f.text_field :response_post_url, class: 'form-control', placeholder: 'e.g. [protocol]://[site address]/azuls/response_post'
      .field.authform-fieldset
        = f.label :custom_field_1
        = f.text_field :custom_field_1, class: 'form-control', placeholder: 'e.g. 1 or 0'
      .field.authform-fieldset
        = f.label :custom_field_1_label
        = f.text_field :custom_field_1_label, class: 'form-control'
      .field.authform-fieldset
        = f.label :custom_field_1_value
        = f.text_field :custom_field_1_value, class: 'form-control'
      .field.authform-fieldset
        = f.label :custom_field_2
        = f.text_field :custom_field_2, class: 'form-control', placeholder: 'e.g. 1 or 0'
      .field.authform-fieldset
        = f.label :custom_field_2_label
        = f.text_field :custom_field_2_label, class: 'form-control'
      .field.authform-fieldset
        = f.label :custom_field_2_value
        = f.text_field :custom_field_2_value, class: 'form-control'
    .form-group.form-group-custom
      .field.authform-fieldset
        = label_tag :amount
        = text_field_tag :amount, '720', html: {class: 'form-control'}
      .field.authform-fieldset
        = label_tag :itbis
        = text_field_tag :itbis, '180', html: {class: 'form-control'}
      .field.authform-fieldset
        = label_tag :order_number
        = text_field_tag :order_number, '1', html: {class: 'form-control'}
      .field.authform-fieldset
        = label_tag :currency
        = text_field_tag :currency, '$', html: {class: 'form-control'}

      = f.submit 'Go to Azul payment page', class: 'button right', id: "button-goto-azul"

  = form_tag 'https://pruebas.azul.com.do/PaymentPage/', method: :post, id: "azul-transaction-form"


:javascript
  $(document).ready(function() {
    $("#button-goto-azul").on('click', function(event) {
      event.preventDefault();

      var merchant_id = $('#azul_merchant_id').val();
      var merchant_type = $('#azul_merchant_type').val();
      var merchant_name = $('#azul_merchant_name').val();
      var auth_key = $('#azul_auth_key').val();
      var url_azul = $('#azul_url_azul').val();
      var approved_url = $('#azul_approved_url').val();
      var declined_url = $('#azul_declined_url').val();
      var cancel_url = $('#azul_cancel_url').val();
      var response_post_url = $('#azul_response_post_url').val();
      var custom_field_1 = $('#azul_custom_field_1').val();
      var custom_field_1_label = $('#azul_custom_field_1_label').val();
      var custom_field_1_value = $('#azul_custom_field_1_value').val();
      var custom_field_2 = $('#azul_custom_field_2').val();
      var custom_field_2_label = $('#azul_custom_field_2_label').val();
      var custom_field_2_value = $('#azul_custom_field_2_value').val();
      var amount = $('#amount').val();
      var itbis = $('#itbis').val();
      var order_number = $('#order_number').val();
      var currency = $('#currency').val();

      remove_all_child_elements_from_transaction_form();
      add_property_into_azul_transaction_form("MerchantId", "MerchantId", merchant_id);
      add_property_into_azul_transaction_form("MerchantName", "MerchantName", merchant_name);
      add_property_into_azul_transaction_form("MerchantType", "MerchantType", merchant_type);
      add_property_into_azul_transaction_form("CurrencyCode", "CurrencyCode", currency);
      add_property_into_azul_transaction_form("itbis", "itbis", itbis);
      add_property_into_azul_transaction_form("OrderNumber", "OrderNumber", order_number);
      add_property_into_azul_transaction_form("Amount", "Amount", amount);
      add_property_into_azul_transaction_form("ApprovedUrl", "ApprovedUrl", approved_url);
      add_property_into_azul_transaction_form("DeclinedUrl", "DeclinedUrl", declined_url);
      add_property_into_azul_transaction_form("CancelUrl", "CancelUrl", declined_url);
      add_property_into_azul_transaction_form("ResponsePostUrl", "ResponsePostUrl", response_post_url);
      add_property_into_azul_transaction_form("UseCustomField1", "UseCustomField1", '1');
      add_property_into_azul_transaction_form("CustomField1Label", "CustomField1Label", 'test1');
      add_property_into_azul_transaction_form("CustomField1Value", "CustomField1Value", 't1');
      add_property_into_azul_transaction_form("UseCustomField2", "UseCustomField2", '1');
      add_property_into_azul_transaction_form("CustomField2Label", "CustomField2Label", 'test2');
      add_property_into_azul_transaction_form("CustomField2Value", "CustomField2Value", 't2');

      $.get('/azuls/get_auth_hash?' + 'merchant_id=' + merchant_id +
        '&merchant_type=' + merchant_type +
        '&merchant_name=' + merchant_name +
        '&auth_key=' + auth_key +
        '&url_azul=' + url_azul +
        '&approved_url=' + approved_url +
        '&declined_url=' + declined_url +
        '&cancel_url=' + cancel_url +
        '&response_post_url=' + response_post_url +
        '&custom_field_1=' + custom_field_1 +
        '&custom_field_1_label=' + custom_field_1_label +
        '&custom_field_1_value=' + custom_field_1_value +
        '&custom_field_2=' + custom_field_2 +
        '&custom_field_2_label=' + custom_field_2_label +
        '&custom_field_2_value=' + custom_field_2_value +
        '&amount=' + amount +
        '&itbis=' + itbis +
        '&order_number=' + order_number +
        '&currency=' + currency,
        function (data) {
          add_property_into_azul_transaction_form("AuthHash", "AuthHash", data.auth_hash);
          var str_result = "Original data for AuthHash: \n" + data.origin_auth + "\n\n" +
                           "AuthHash: \n" + data.auth_hash + "\n\n" +
                           "Form data: \n" + $("#azul-transaction-form").serialize()
          alert(str_result);
          $("#azul-transaction-form").submit();
        });

    });

    function add_property_into_azul_transaction_form(id, name, value) {
      console.log(id, name, value);
      if(typeof value === 'undefined') {
        value = '';
      }
      var input = $("<input/>", {type: "hidden", id: id, name: name, value:     value});
      $("#azul-transaction-form").append(input);
    }

    function remove_all_child_elements_from_transaction_form() {
      $("#azul-transaction-form").empty();
    }
  });

app/views/azuls/api_mode.html.haml
.authform.authform-wide
  %h3 AZUL API mode with JSON data

  = render 'form_for_api_mode'

  = link_to 'Show', @azul
  \|
  = link_to 'Back', azuls_path

app/views/azuls/approved.html.haml
= "Approved"

app/views/azuls/canceled.html.haml
= "Canceled"

app/views/azuls/edit.html.haml
%h1 Editing azul

= render 'form'

= link_to 'Show', @azul
\|
= link_to 'Back', azuls_path

app/views/azuls/index.html.haml
%h1 Listing azuls

%table
  %thead
    %tr
      %th Merchant
      %th Merchant type
      %th Merchant name
      %th Auth key
      %th Url azul
      %th Approved url
      %th Declined url
      %th Cancel url
      %th Response post url
      %th
      %th
      %th

  %tbody
    - @azuls.each do |azul|
      %tr
        %td= azul.merchant_id
        %td= azul.merchant_type
        %td= azul.merchant_name
        %td= azul.auth_key
        %td= azul.url_azul
        %td= azul.approved_url
        %td= azul.declined_url
        %td= azul.cancel_url
        %td= azul.response_post_url
        %td= link_to 'Show', azul
        %td= link_to 'Edit', edit_azul_path(azul)
        %td= link_to 'Destroy', azul, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Azul', new_azul_path

app/views/azuls/make_payment_by_azul_api.html.haml
= "made payment by azul api with json data"

app/views/azuls/new.html.haml
%h1 New azul

= render 'form'

= link_to 'Back', azuls_path

app/views/azuls/page_forwarding_mode.html.haml
.authform.authform-wide
  %h3 AZUL page forwarding mode

  = render 'form_for_page_forwarding_mode'

  -# = link_to 'Show', @azul
  -# |
  -# = link_to 'Back', azuls_path

app/views/azuls/response_post.html.haml
= "Got response"

app/views/azuls/show.html.haml
%p#notice= notice

%p
  %b Merchant:
  = @azul.merchant_id
%p
  %b Merchant type:
  = @azul.merchant_type
%p
  %b Merchant name:
  = @azul.merchant_name
%p
  %b Auth key:
  = @azul.auth_key
%p
  %b Url azul:
  = @azul.url_azul
%p
  %b Approved url:
  = @azul.approved_url
%p
  %b Declined url:
  = @azul.declined_url
%p
  %b Cancel url:
  = @azul.cancel_url
%p
  %b Response post url:
  = @azul.response_post_url

= link_to 'Edit', edit_azul_path(@azul)
\|
= link_to 'Back', azuls_path