config/routes.rb
Rails.application.routes.draw do
  resources :azuls do
    collection do
      get 'page_forwarding_mode'
      post 'forward_to_azul_payment_page'
      get 'approved'
      get 'declined'
      get 'canceled'
      post 'response_post'
      get 'api_mode'
      post 'make_payment_by_azul_api'
      get 'get_auth_hash'
    end
  end
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'azuls#page_forwarding_mode'
  devise_for :users
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item active'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item active'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item active'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item active'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
-#.container
%nav.navbar.navbar-expand-md.navbar-toggler-right.navbar-dark.fixed-top.bg-dark.navbar-inverse{role: :navigation}
  .container.contianer_fluid
    .navbar-header
      %ul.nav.navbar-nav.clearfix
        %li.nav-item
          %button.navbar-toggler.collapsed.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
            \ &#9776;
      = link_to "AZUL payment", root_path, class: 'navbar-brand'

    #navbarCollapse.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        = render 'layouts/navigation_links'
      %ul.navbar-nav.justify-content-end
        = render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item active'><%= link_to 'Home', root_path, class: 'nav-link' %></li>
<% if user_signed_in? %>
<li class='nav-item active'><%= link_to 'PageForwarding-Mode', page_forwarding_mode_azuls_path, class: 'nav-link' %></li>
<li class='nav-item active'><%= link_to 'API-Mode', api_mode_azuls_path, class: 'nav-link' %></li>
<% end %>
<li class='nav-item active'><%= link_to 'About', '#', class: 'nav-link' %></li>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Rails Azul Payment Integration'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Rails Azul Payment Integration'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:class => "main-window", :role => "main"}
      = render 'layouts/messages'
      = yield